//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RdlMapFile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RdlMapFile.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MapData XML file doesn&apos;t contain the &apos;MapData&apos; element.
        /// </summary>
        internal static string DesignXmlDraw_Error_XMLNotMapData {
            get {
                return ResourceManager.GetString("DesignXmlDraw_Error_XMLNotMapData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Opening File.
        /// </summary>
        internal static string DesignXmlDraw_SetMapFile_ErrorOpeningFile {
            get {
                return ResourceManager.GetString("DesignXmlDraw_SetMapFile_ErrorOpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open file.
        /// </summary>
        internal static string DesignXmlDraw_SetMapFile_Unable_to_open_file {
            get {
                return ResourceManager.GetString("DesignXmlDraw_SetMapFile_Unable_to_open_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DesignXmlDraw_Undo_Delete {
            get {
                return ResourceManager.GetString("DesignXmlDraw_Undo_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Line Point.
        /// </summary>
        internal static string DesignXmlDraw_Undo_InsertLinePoint {
            get {
                return ResourceManager.GetString("DesignXmlDraw_Undo_InsertLinePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Polygon Point.
        /// </summary>
        internal static string DesignXmlDraw_Undo_InsertPolygonPoint {
            get {
                return ResourceManager.GetString("DesignXmlDraw_Undo_InsertPolygonPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Text.
        /// </summary>
        internal static string DesignXmlDraw_Undo_InsertText {
            get {
                return ResourceManager.GetString("DesignXmlDraw_Undo_InsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string DesignXmlDraw_Undo_Move {
            get {
                return ResourceManager.GetString("DesignXmlDraw_Undo_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string DesignXmlDraw_Undo_Paste {
            get {
                return ResourceManager.GetString("DesignXmlDraw_Undo_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce Point Count.
        /// </summary>
        internal static string DesignXmlDraw_Undo_ReducePointCount {
            get {
                return ResourceManager.GetString("DesignXmlDraw_Undo_ReducePointCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        internal static string DesignXmlDraw_Undo_Resize {
            get {
                return ResourceManager.GetString("DesignXmlDraw_Undo_Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map File Designer creates XML files that can be used in map Charts within the RDL designer.
        ///
        ///Copyright (C) 2004-2008  fyiReporting Software, LLC
        ///	
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        ///you may not use this file except in compliance with the License.
        ///You may obtain a copy of the License at
        ///
        ///http://www.apache.org/licenses/LICENSE-2.0
        ///
        ///Unless required by applicable law or agreed to in writing, software
        ///distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
        ///WITHO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DialogAbout_About {
            get {
                return ResourceManager.GetString("DialogAbout_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string DialogAbout_Version {
            get {
                return ResourceManager.GetString("DialogAbout_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string MapFile_editToolStripMenuItem_DropDownOpening_Undo {
            get {
                return ResourceManager.GetString("MapFile_editToolStripMenuItem_DropDownOpening_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help URL Invalid.
        /// </summary>
        internal static string MapFile_helpHelpToolStripMenuItem_Click_Help_URL_Invalid {
            get {
                return ResourceManager.GetString("MapFile_helpHelpToolStripMenuItem_Click_Help_URL_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape Files (*.shp)|*.shp|All files (*.*)|*.*.
        /// </summary>
        internal static string MapFile_importMenuItem_Click_OpenShape {
            get {
                return ResourceManager.GetString("MapFile_importMenuItem_Click_OpenShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening.
        /// </summary>
        internal static string MapFile_openToolStripMenuItem_Click_ErrorOpening {
            get {
                return ResourceManager.GetString("MapFile_openToolStripMenuItem_Click_ErrorOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string MapFile_openToolStripMenuItem_Click_OpenMap {
            get {
                return ResourceManager.GetString("MapFile_openToolStripMenuItem_Click_OpenMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce Polygon Count.
        /// </summary>
        internal static string MapFile_reducePolygonPointsToolStripMenuItem_Click_Reduce_Polygon_Count {
            get {
                return ResourceManager.GetString("MapFile_reducePolygonPointsToolStripMenuItem_Click_Reduce_Polygon_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon point count reduced by.
        /// </summary>
        internal static string MapFile_reducePolygonPointsToolStripMenuItem_ReducePolygon {
            get {
                return ResourceManager.GetString("MapFile_reducePolygonPointsToolStripMenuItem_ReducePolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDL Map files (*.xml)|*.xml|All files (*.*)|*.*.
        /// </summary>
        internal static string MapFile_SaveAs_RDL_MapFilesFilter {
            get {
                return ResourceManager.GetString("MapFile_SaveAs_RDL_MapFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap Files (*.bmp)|*.bmp|JPEG (*.jpg;*.jpeg;*.jpe;*.jfif)|*.jpg;*.jpeg;*.jpe;*.jfif|GIF (*.gif)|*.gif|TIFF (*.tif;*.tiff)|*.tif;*.tiff|PNG (*.png)|*.png|All Picture Files|*.bmp;*.jpg;*.jpeg;*.jpe;*.jfif;*.gif;*.tif;*.tiff;*.png|All files (*.*)|*.*.
        /// </summary>
        internal static string MapFile_setBackgroundImageToolStripMenuItem_Click_OpenPicture {
            get {
                return ResourceManager.GetString("MapFile_setBackgroundImageToolStripMenuItem_Click_OpenPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fyiReporting MapFile Designer.
        /// </summary>
        internal static string MapFile_SetTitle_fyiReporting_MapFile_Designer {
            get {
                return ResourceManager.GetString("MapFile_SetTitle_fyiReporting_MapFile_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to untitled.
        /// </summary>
        internal static string MapFile_SetTitle_untitled {
            get {
                return ResourceManager.GetString("MapFile_SetTitle_untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RdlMapFile designer.
        /// </summary>
        internal static string MapFile_ShowB_RdlMapFileDesigner {
            get {
                return ResourceManager.GetString("MapFile_ShowB_RdlMapFileDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to untitled.
        /// </summary>
        internal static string MapFile_ShowB_Untitled {
            get {
                return ResourceManager.GetString("MapFile_ShowB_Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes you made to &apos;{0}&apos;?.
        /// </summary>
        internal static string MapFile_ShowB_WantSave {
            get {
                return ResourceManager.GetString("MapFile_ShowB_WantSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support URL Invalid.
        /// </summary>
        internal static string MapFile_supportToolStripMenuItem_Click_Support_URL_Invalid {
            get {
                return ResourceManager.GetString("MapFile_supportToolStripMenuItem_Click_Support_URL_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        internal static string NodeChangedUndo_Undo_change {
            get {
                return ResourceManager.GetString("NodeChangedUndo_Undo_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert.
        /// </summary>
        internal static string NodeInsertedUndo_Undo_insert {
            get {
                return ResourceManager.GetString("NodeInsertedUndo_Undo_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        internal static string NodeRemovedUndo_Undo_remove {
            get {
                return ResourceManager.GetString("NodeRemovedUndo_Undo_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        internal static string PropertyBase_Undo_change {
            get {
                return ResourceManager.GetString("PropertyBase_Undo_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font change.
        /// </summary>
        internal static string PropertyText_Undo_FontChange {
            get {
                return ResourceManager.GetString("PropertyText_Undo_FontChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid FileCode encountered. Expecting {0}..
        /// </summary>
        internal static string ShapeFile_ErrorA_InvalidFileCode {
            get {
                return ResourceManager.GetString("ShapeFile_ErrorA_InvalidFileCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShapeType {0} is not supported..
        /// </summary>
        internal static string ShapeFile_ErrorA_ShapeTypeNotSupported {
            get {
                return ResourceManager.GetString("ShapeFile_ErrorA_ShapeTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal logic error: EndGroup doesn&apos;t match StartGroup.
        /// </summary>
        internal static string Undo_Error_EndGroupNotMatchStartGroup {
            get {
                return ResourceManager.GetString("Undo_Error_EndGroupNotMatchStartGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Action.
        /// </summary>
        internal static string Undo_Error_UnknownAction {
            get {
                return ResourceManager.GetString("Undo_Error_UnknownAction", resourceCulture);
            }
        }
    }
}
