
// This file has been generated by the GUI designer. Do not modify.
namespace fyiReporting.RdlGtkViewer
{
	public partial class RdlGtkViewer
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button SaveButton;
		private global::Gtk.Button PrintButton;
		private global::Gtk.Button FirstPageButton;
		private global::Gtk.Button PreviousButton;
		private global::Gtk.Button NextButton;
		private global::Gtk.Button LastPageButton;
		private global::Gtk.SpinButton CurrentPage;
		private global::Gtk.Label PageCountLabel;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.VBox vboxImages;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget fyiReporting.RdlGtkViewer.RdlGtkViewer
			global::Stetic.BinContainer.Attach (this);
			this.Name = "fyiReporting.RdlGtkViewer.RdlGtkViewer";
			// Container child fyiReporting.RdlGtkViewer.RdlGtkViewer.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.SaveButton = new global::Gtk.Button ();
			this.SaveButton.CanFocus = true;
			this.SaveButton.Name = "SaveButton";
			this.SaveButton.UseStock = true;
			this.SaveButton.UseUnderline = true;
			this.SaveButton.Label = "gtk-save";
			this.hbox1.Add (this.SaveButton);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.SaveButton]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.PrintButton = new global::Gtk.Button ();
			this.PrintButton.CanFocus = true;
			this.PrintButton.Name = "PrintButton";
			this.PrintButton.UseStock = true;
			this.PrintButton.UseUnderline = true;
			this.PrintButton.Label = "gtk-print";
			this.hbox1.Add (this.PrintButton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.PrintButton]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.FirstPageButton = new global::Gtk.Button ();
			this.FirstPageButton.CanFocus = true;
			this.FirstPageButton.Name = "FirstPageButton";
			this.FirstPageButton.UseStock = true;
			this.FirstPageButton.UseUnderline = true;
			this.FirstPageButton.Label = "gtk-goto-first";
			this.hbox1.Add (this.FirstPageButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.FirstPageButton]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.PreviousButton = new global::Gtk.Button ();
			this.PreviousButton.CanFocus = true;
			this.PreviousButton.Name = "PreviousButton";
			this.PreviousButton.UseStock = true;
			this.PreviousButton.UseUnderline = true;
			this.PreviousButton.Label = "gtk-go-back";
			this.hbox1.Add (this.PreviousButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.PreviousButton]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.NextButton = new global::Gtk.Button ();
			this.NextButton.CanFocus = true;
			this.NextButton.Name = "NextButton";
			this.NextButton.UseStock = true;
			this.NextButton.UseUnderline = true;
			this.NextButton.Label = "gtk-go-forward";
			this.hbox1.Add (this.NextButton);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.NextButton]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.LastPageButton = new global::Gtk.Button ();
			this.LastPageButton.CanFocus = true;
			this.LastPageButton.Name = "LastPageButton";
			this.LastPageButton.UseStock = true;
			this.LastPageButton.UseUnderline = true;
			this.LastPageButton.Label = "gtk-goto-last";
			this.hbox1.Add (this.LastPageButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.LastPageButton]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.CurrentPage = new global::Gtk.SpinButton (0, 999999, 1);
			this.CurrentPage.CanFocus = true;
			this.CurrentPage.Name = "CurrentPage";
			this.CurrentPage.Adjustment.PageIncrement = 10;
			this.CurrentPage.ClimbRate = 1;
			this.CurrentPage.Numeric = true;
			this.hbox1.Add (this.CurrentPage);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.CurrentPage]));
			w7.Position = 6;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.PageCountLabel = new global::Gtk.Label ();
			this.PageCountLabel.Name = "PageCountLabel";
			this.hbox1.Add (this.PageCountLabel);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.PageCountLabel]));
			w8.Position = 7;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w10 = new global::Gtk.Viewport ();
			w10.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vboxImages = new global::Gtk.VBox ();
			this.vboxImages.Name = "vboxImages";
			this.vboxImages.Spacing = 6;
			w10.Add (this.vboxImages);
			this.scrolledwindow1.Add (w10);
			this.vbox1.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.scrolledwindow1]));
			w13.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.SaveButton.Clicked += new global::System.EventHandler (this.OnSaveButtonClicked);
			this.PrintButton.Clicked += new global::System.EventHandler (this.OnPrintButtonClicked);
			this.FirstPageButton.Clicked += new global::System.EventHandler (this.OnFirstPageButtonClicked);
			this.PreviousButton.Clicked += new global::System.EventHandler (this.OnPreviousButtonClicked);
			this.NextButton.Clicked += new global::System.EventHandler (this.OnNextButtonClicked);
			this.LastPageButton.Clicked += new global::System.EventHandler (this.OnLastPageButtonClicked);
			this.CurrentPage.ValueChanged += new global::System.EventHandler (this.OnCurrentPageValueChanged);
		}
	}
}
