//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RdlEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RdlEngine.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error : FileReader.UnGet : ungetted first char.
        /// </summary>
        internal static string CharReader_Error_FileReaderUnGetFirstChar {
            get {
                return ResourceManager.GetString("CharReader_Error_FileReaderUnGetFirstChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot area height is less than or equal to 0.
        /// </summary>
        internal static string ChartLayout_Error_PlotAreaHeightIs0 {
            get {
                return ResourceManager.GetString("ChartLayout_Error_PlotAreaHeightIs0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot area width is less than or equal to 0.
        /// </summary>
        internal static string ChartLayout_Error_PlotAreaWidthIs0 {
            get {
                return ResourceManager.GetString("ChartLayout_Error_PlotAreaWidthIs0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password provided for shared DataSource reference.
        /// </summary>
        internal static string DataSourceDefn_Error_NoPasswordForDSR {
            get {
                return ResourceManager.GetString("DataSourceDefn_Error_NoPasswordForDSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter operators TopN and BottomN require an integer value got {0}..
        /// </summary>
        internal static string Filter_Error_TopNAndBottomNRequireInt {
            get {
                return ResourceManager.GetString("Filter_Error_TopNAndBottomNRequireInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPmt doesn&apos;t support payments due at beginning of period..
        /// </summary>
        internal static string Financial_Error_IPmtNotSupportPayments {
            get {
                return ResourceManager.GetString("Financial_Error_IPmtNotSupportPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} method not found in code.
        /// </summary>
        internal static string FunctionCode_Error_MethodNotFound {
            get {
                return ResourceManager.GetString("FunctionCode_Error_MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} method not found in class {1}.
        /// </summary>
        internal static string FunctionCustomInstance_Error_MethodNotFoundInClass {
            get {
                return ResourceManager.GetString("FunctionCustomInstance_Error_MethodNotFoundInClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} method not found in class {1}.
        /// </summary>
        internal static string FunctionCustomStatic_Error_MethodNotFoundInClass {
            get {
                return ResourceManager.GetString("FunctionCustomStatic_Error_MethodNotFoundInClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field collection argument {0} is invalid.
        /// </summary>
        internal static string FunctionFieldCollection_Error_FieldCollectionInvalid {
            get {
                return ResourceManager.GetString("FunctionFieldCollection_Error_FieldCollectionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field collection argument is null.
        /// </summary>
        internal static string FunctionFieldCollection_Error_FieldCollectionNull {
            get {
                return ResourceManager.GetString("FunctionFieldCollection_Error_FieldCollectionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globals collection argument is null.
        /// </summary>
        internal static string FunctionGlobalCollection_Error_GlobalsNull {
            get {
                return ResourceManager.GetString("FunctionGlobalCollection_Error_GlobalsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globals collection argument &apos;{0}&apos; is unknown..
        /// </summary>
        internal static string FunctionGlobalCollection_Error_GlobalsUnknown {
            get {
                return ResourceManager.GetString("FunctionGlobalCollection_Error_GlobalsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter collection argument {0} is invalid.
        /// </summary>
        internal static string FunctionParameterCollection_Error_ParameterCollectionInvalid {
            get {
                return ResourceManager.GetString("FunctionParameterCollection_Error_ParameterCollectionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter collection argument is null.
        /// </summary>
        internal static string FunctionParameterCollection_Error_ParameterCollectionNull {
            get {
                return ResourceManager.GetString("FunctionParameterCollection_Error_ParameterCollectionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportItem collection argument {0} is invalid.
        /// </summary>
        internal static string FunctionReportItemCollection_Error_ReportItemCollectionInvalid {
            get {
                return ResourceManager.GetString("FunctionReportItemCollection_Error_ReportItemCollectionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportItem collection argument is null.
        /// </summary>
        internal static string FunctionReportItemCollection_Error_ReportItemCollectionNull {
            get {
                return ResourceManager.GetString("FunctionReportItemCollection_Error_ReportItemCollectionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: unknown Report Parameter method.
        /// </summary>
        internal static string FunctionReportParameter_Error_UnknownReporParameterMethod {
            get {
                return ResourceManager.GetString("FunctionReportParameter_Error_UnknownReporParameterMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} method not found in class {1}.
        /// </summary>
        internal static string FunctionSystem_Error_MethodNotFound {
            get {
                return ResourceManager.GetString("FunctionSystem_Error_MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User collection argument {0} is invalid..
        /// </summary>
        internal static string FunctionUserCollection_Error_UserCollectionInvalid {
            get {
                return ResourceManager.GetString("FunctionUserCollection_Error_UserCollectionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User collection argument is null.
        /// </summary>
        internal static string FunctionUserCollection_Error_UserCollectionNull {
            get {
                return ResourceManager.GetString("FunctionUserCollection_Error_UserCollectionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid conversion from Language to boolean..
        /// </summary>
        internal static string FunctionUserLanguage_Error_ConvertToBoolean {
            get {
                return ResourceManager.GetString("FunctionUserLanguage_Error_ConvertToBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid conversion from Language to DateTime..
        /// </summary>
        internal static string FunctionUserLanguage_Error_ConvertToDateTime {
            get {
                return ResourceManager.GetString("FunctionUserLanguage_Error_ConvertToDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid conversion from Language to Decimal..
        /// </summary>
        internal static string FunctionUserLanguage_Error_ConvertToDecimal {
            get {
                return ResourceManager.GetString("FunctionUserLanguage_Error_ConvertToDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid conversion from Language to double..
        /// </summary>
        internal static string FunctionUserLanguage_Error_ConvertToDouble {
            get {
                return ResourceManager.GetString("FunctionUserLanguage_Error_ConvertToDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid conversion from Language to Int32..
        /// </summary>
        internal static string FunctionUserLanguage_Error_ConvertToInt32 {
            get {
                return ResourceManager.GetString("FunctionUserLanguage_Error_ConvertToInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; should be followed by a number.
        /// </summary>
        internal static string Lexer_Error_SeparatorMustFollowedNumber {
            get {
                return ResourceManager.GetString("Lexer_Error_SeparatorMustFollowedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated comment!.
        /// </summary>
        internal static string Lexer_Error_UnterminatedComment {
            get {
                return ResourceManager.GetString("Lexer_Error_UnterminatedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number constant..
        /// </summary>
        internal static string Lexer_ErrorP_InvalidNumberConstant {
            get {
                return ResourceManager.GetString("Lexer_ErrorP_InvalidNumberConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string!.
        /// </summary>
        internal static string Lexer_ErrorP_UnterminatedString {
            get {
                return ResourceManager.GetString("Lexer_ErrorP_UnterminatedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension of the filename provided + &apos;{0}&apos;, does not have the expected extension(s) &apos;{1}&apos;.
        /// </summary>
        internal static string MhtBuilder_Error_Extension {
            get {
                return ResourceManager.GetString("MhtBuilder_Error_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filename provided, &apos;{0}&apos;, has no extension. If are specifying a folder, make sure it ends in a trailing slash. The expected file extension(s) are &apos;{1}&apos;.
        /// </summary>
        internal static string MhtBuilder_Error_FilenameNoExtension {
            get {
                return ResourceManager.GetString("MhtBuilder_Error_FilenameNoExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to download &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string MhtBuilder_Error_UnableDownload {
            get {
                return ResourceManager.GetString("MhtBuilder_Error_UnableDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converting references only makes sense for HTML or CSS files; this file is of type &apos;{0}&apos;.
        /// </summary>
        internal static string MhtWebFile_Error_ConvertOnlyHTMLOrCSS {
            get {
                return ResourceManager.GetString("MhtWebFile_Error_ConvertOnlyHTMLOrCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filename was provided, and the HTML title tag was not found, so a filename could not be automatically generated. You&apos;ll need to provide a filename and not a folder..
        /// </summary>
        internal static string MhtWebFile_Error_NoFilename {
            get {
                return ResourceManager.GetString("MhtWebFile_Error_NoFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} already exists..
        /// </summary>
        internal static string OneFileStreamGen_Error_FileAlreadyExists {
            get {
                return ResourceManager.GetString("OneFileStreamGen_Error_FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentPage must be in the list of pages.
        /// </summary>
        internal static string Pages_Error_CurrentPageMustInList {
            get {
                return ResourceManager.GetString("Pages_Error_CurrentPageMustInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build method must be called prior to referencing TotalHeight..
        /// </summary>
        internal static string PageTextHtml_Error_BuildMethodMustCalledPriorTotalHeight {
            get {
                return ResourceManager.GetString("PageTextHtml_Error_BuildMethodMustCalledPriorTotalHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate function &apos;{0}&apos; cannot be nested in another aggregate function..
        /// </summary>
        internal static string Parser_ErrorP_AggregateCannotNestedInAnotherAggregate {
            get {
                return ResourceManager.GetString("Parser_ErrorP_AggregateCannotNestedInAnotherAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate function &apos;{0}&apos; cannot be used within a Grouping expression..
        /// </summary>
        internal static string Parser_ErrorP_AggregateCannotUsedWithinGrouping {
            get {
                return ResourceManager.GetString("Parser_ErrorP_AggregateCannotUsedWithinGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregate function must have at least one argument..
        /// </summary>
        internal static string Parser_ErrorP_AggregateMust1Argument {
            get {
                return ResourceManager.GetString("Parser_ErrorP_AggregateMust1Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND/OR operations require both sides to be boolean expressions..
        /// </summary>
        internal static string Parser_ErrorP_AND_OR_RequiresBoolean {
            get {
                return ResourceManager.GetString("Parser_ErrorP_AND_OR_RequiresBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   At column {0}.
        /// </summary>
        internal static string Parser_ErrorP_AtColumn {
            get {
                return ResourceManager.GetString("Parser_ErrorP_AtColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;)&apos; expected but not found..
        /// </summary>
        internal static string Parser_ErrorP_BracketExpected {
            get {
                return ResourceManager.GetString("Parser_ErrorP_BracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First argument to Choose function must be numeric..
        /// </summary>
        internal static string Parser_ErrorP_ChooseFirstArgumentMustNumeric {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ChooseFirstArgumentMustNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose function requires at least 2 arguments..
        /// </summary>
        internal static string Parser_ErrorP_ChooseRequires2Arguments {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ChooseRequires2Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} is not known..
        /// </summary>
        internal static string Parser_ErrorP_ClassUnknown {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ClassUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;}&apos; expected but not found..
        /// </summary>
        internal static string Parser_ErrorP_CurlyBracketExpected {
            get {
                return ResourceManager.GetString("Parser_ErrorP_CurlyBracketExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End of expression expected..
        /// </summary>
        internal static string Parser_ErrorP_EndExpressionExpected {
            get {
                return ResourceManager.GetString("Parser_ErrorP_EndExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting &apos;,&apos; or &apos;)&apos;..
        /// </summary>
        internal static string Parser_ErrorP_ExpectingComma {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ExpectingComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos;  not found..
        /// </summary>
        internal static string Parser_ErrorP_FieldNotFound {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; is not in DataSet {1}..
        /// </summary>
        internal static string Parser_ErrorP_FieldNotInDataSet {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FieldNotInDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields collection requires exactly 1 argument..
        /// </summary>
        internal static string Parser_ErrorP_FieldsRequires1Argument {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FieldsRequires1Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos;  only supports &apos;Value&apos; and &apos;IsMissing&apos; properties..
        /// </summary>
        internal static string Parser_ErrorP_FieldSupportsValueAndIsMissing {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FieldSupportsValueAndIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format function requires 2 arguments..
        /// </summary>
        internal static string Parser_ErrorP_FormatRequires2Arguments {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FormatRequires2Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Found &apos;{0}&apos;.
        /// </summary>
        internal static string Parser_ErrorP_FoundValue {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FoundValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; of class &apos;{1}&apos; is not known..
        /// </summary>
        internal static string Parser_ErrorP_FunctionOfClassUnknown {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FunctionOfClassUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function {0} is not known..
        /// </summary>
        internal static string Parser_ErrorP_FunctionUnknown {
            get {
                return ResourceManager.GetString("Parser_ErrorP_FunctionUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globals &apos;{0}&apos;  not found..
        /// </summary>
        internal static string Parser_ErrorP_GlobalsNotFound {
            get {
                return ResourceManager.GetString("Parser_ErrorP_GlobalsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Globals collection requires exactly 1 argument..
        /// </summary>
        internal static string Parser_ErrorP_GlobalsRequires1Argument {
            get {
                return ResourceManager.GetString("Parser_ErrorP_GlobalsRequires1Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant or Identifier expected but not found..
        /// </summary>
        internal static string Parser_ErrorP_IdentifierExpected {
            get {
                return ResourceManager.GetString("Parser_ErrorP_IdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iff function requires 3 arguments..
        /// </summary>
        internal static string Parser_ErrorP_iff_function_requires_3_arguments {
            get {
                return ResourceManager.GetString("Parser_ErrorP_iff_function_requires_3_arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid function arguments..
        /// </summary>
        internal static string Parser_ErrorP_Invalid_function_arguments {
            get {
                return ResourceManager.GetString("Parser_ErrorP_Invalid_function_arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportItem &apos;{0}&apos;  not found..
        /// </summary>
        internal static string Parser_ErrorP_ItemNotFound {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportItem &apos;{0}&apos;  only supports &apos;Value&apos; property..
        /// </summary>
        internal static string Parser_ErrorP_ItemSupportsValue {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ItemSupportsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;-&apos; operator works only on numbers..
        /// </summary>
        internal static string Parser_ErrorP_MinusNeedNumbers {
            get {
                return ResourceManager.GetString("Parser_ErrorP_MinusNeedNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scope provided for aggregate function &apos;{0}&apos; but more than one DataSet defined..
        /// </summary>
        internal static string Parser_ErrorP_NoScope4Aggregate {
            get {
                return ResourceManager.GetString("Parser_ErrorP_NoScope4Aggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a Code method.  Verify the name of the method and its arguments match an existing code function..
        /// </summary>
        internal static string Parser_ErrorP_NotCodeMethod {
            get {
                return ResourceManager.GetString("Parser_ErrorP_NotCodeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT requires boolean expression..
        /// </summary>
        internal static string Parser_ErrorP_NOTRequiresBoolean {
            get {
                return ResourceManager.GetString("Parser_ErrorP_NOTRequiresBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report parameter &apos;{0}&apos;  not found..
        /// </summary>
        internal static string Parser_ErrorP_ParameterNotFound {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters collection requires exactly 1 argument..
        /// </summary>
        internal static string Parser_ErrorP_ParametersRequires1Argument {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ParametersRequires1Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos;  only supports &apos;Value&apos; and &apos;Label&apos; properties..
        /// </summary>
        internal static string Parser_ErrorP_ParameterSupportsValueAndLabel {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ParameterSupportsValueAndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportItems collection requires exactly 1 argument..
        /// </summary>
        internal static string Parser_ErrorP_ReportItemsRequires1Argument {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ReportItemsRequires1Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunningValue takes 2 or 3 arguments..
        /// </summary>
        internal static string Parser_ErrorP_RunningValue_takes_2_or_3_arguments {
            get {
                return ResourceManager.GetString("Parser_ErrorP_RunningValue_takes_2_or_3_arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunningValue &apos;Function&apos; argument is invalid..
        /// </summary>
        internal static string Parser_ErrorP_RunningValueArgumentInvalid {
            get {
                return ResourceManager.GetString("Parser_ErrorP_RunningValueArgumentInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RunningValue function &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string Parser_ErrorP_RunningValueNotSupported {
            get {
                return ResourceManager.GetString("Parser_ErrorP_RunningValueNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal scope identifer specified..
        /// </summary>
        internal static string Parser_ErrorP_ScopeIdentifer {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ScopeIdentifer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} function&apos;s scope must be a constant..
        /// </summary>
        internal static string Parser_ErrorP_ScopeMustConstant {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ScopeMustConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope &apos;{0}&apos; does not reference a known DataSet..
        /// </summary>
        internal static string Parser_ErrorP_ScopeNotKnownDataSet {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ScopeNotKnownDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope &apos;{0}&apos; is not a known Grouping, DataSet or DataRegion name..
        /// </summary>
        internal static string Parser_ErrorP_ScopeNotKnownGrouping {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ScopeNotKnownGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope &apos;{0}&apos; can&apos;t be specified in a Page Header or Footer expression..
        /// </summary>
        internal static string Parser_ErrorP_ScopeNotSpecifiedInHeaderOrFooter {
            get {
                return ResourceManager.GetString("Parser_ErrorP_ScopeNotSpecifiedInHeaderOrFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second argument to Format function must be a string..
        /// </summary>
        internal static string Parser_ErrorP_SecondMustString {
            get {
                return ResourceManager.GetString("Parser_ErrorP_SecondMustString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch function must have a boolean expression every other argument..
        /// </summary>
        internal static string Parser_ErrorP_SwitchMustBoolean {
            get {
                return ResourceManager.GetString("Parser_ErrorP_SwitchMustBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch function must have an even number of arguments..
        /// </summary>
        internal static string Parser_ErrorP_SwitchMustEvenArguments {
            get {
                return ResourceManager.GetString("Parser_ErrorP_SwitchMustEvenArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch function requires at least 2 arguments..
        /// </summary>
        internal static string Parser_ErrorP_SwitchRequires2Arguments {
            get {
                return ResourceManager.GetString("Parser_ErrorP_SwitchRequires2Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an unknown identifer..
        /// </summary>
        internal static string Parser_ErrorP_UnknownIdentifer {
            get {
                return ResourceManager.GetString("Parser_ErrorP_UnknownIdentifer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a known property for {1}..
        /// </summary>
        internal static string Parser_ErrorP_UnknownProperty {
            get {
                return ResourceManager.GetString("Parser_ErrorP_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User collection requires exactly 1 argument..
        /// </summary>
        internal static string Parser_ErrorP_UserRequires1Argument {
            get {
                return ResourceManager.GetString("Parser_ErrorP_UserRequires1Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User variable &apos;{0}&apos;  not found..
        /// </summary>
        internal static string Parser_ErrorP_UserVarNotFound {
            get {
                return ResourceManager.GetString("Parser_ErrorP_UserVarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetObjectNumber must be called before GetOutlineDict.
        /// </summary>
        internal static string PdfOutline_Error_GetObjectNumberMustBeforeGetOutlineDict {
            get {
                return ResourceManager.GetString("PdfOutline_Error_GetObjectNumberMustBeforeGetOutlineDict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report has errors.  Cannot be processed..
        /// </summary>
        internal static string ProcessReport_Error_ReportHasErrors {
            get {
                return ResourceManager.GetString("ProcessReport_Error_ReportHasErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: XML Data must contain top level rows..
        /// </summary>
        internal static string Query_Error_XMLMustContainTopLevelRows {
            get {
                return ResourceManager.GetString("Query_Error_XMLMustContainTopLevelRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be found.
        /// </summary>
        internal static string RdlEngineConfig_Error_CashModuleNotFound {
            get {
                return ResourceManager.GetString("RdlEngineConfig_Error_CashModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be loaded.
        /// </summary>
        internal static string RdlEngineConfig_Error_CodeModuleNotLoaded {
            get {
                return ResourceManager.GetString("RdlEngineConfig_Error_CodeModuleNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a known CustomReportItem type.
        /// </summary>
        internal static string RdlEngineConfig_Error_NotKnownCustomReportItemType {
            get {
                return ResourceManager.GetString("RdlEngineConfig_Error_NotKnownCustomReportItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create instance of &apos;{0}&apos; for provider &apos;{1}&apos;.
        /// </summary>
        internal static string RdlEngineConfig_Error_UnableCreateInstance {
            get {
                return ResourceManager.GetString("RdlEngineConfig_Error_UnableCreateInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: RDL doesn&apos;t contain a report element. .
        /// </summary>
        internal static string RDLParser_ErrorP__NoReport {
            get {
                return ResourceManager.GetString("RDLParser_ErrorP__NoReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: XML failed .
        /// </summary>
        internal static string RDLParser_ErrorP_XMLFailed {
            get {
                return ResourceManager.GetString("RDLParser_ErrorP_XMLFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string ReportLog_Error_Severity {
            get {
                return ResourceManager.GetString("ReportLog_Error_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subreport {0} doesn&apos;t define parameter {1}..
        /// </summary>
        internal static string Subreport_Error_SubreportNotParameter {
            get {
                return ResourceManager.GetString("Subreport_Error_SubreportNotParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Recursive groups must be the only group definition..
        /// </summary>
        internal static string Table_Error_RecursiveGroupsMustOnlyGroupDefinition {
            get {
                return ResourceManager.GetString("Table_Error_RecursiveGroupsMustOnlyGroupDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: TableRow not related to a Table.
        /// </summary>
        internal static string TableRow_Error_TableRowNotRelatedToTable {
            get {
                return ResourceManager.GetString("TableRow_Error_TableRowNotRelatedToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.  TableRows must be owned eventually by a table..
        /// </summary>
        internal static string TableRows_Error_TableRowsMustOwnedTable {
            get {
                return ResourceManager.GetString("TableRows_Error_TableRowsMustOwnedTable", resourceCulture);
            }
        }
    }
}
