//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RdlMapFile.RdlProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RdlMapFile.RdlProperties.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One end of the line.
        /// </summary>
        internal static string Line_P1 {
            get {
                return ResourceManager.GetString("Line_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other end of the line.
        /// </summary>
        internal static string Line_P2 {
            get {
                return ResourceManager.GetString("Line_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fill color for the polygon.
        /// </summary>
        internal static string Polygon_FillColor {
            get {
                return ResourceManager.GetString("Polygon_FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keys associated with this polygon.
        /// </summary>
        internal static string Polygon_Keys {
            get {
                return ResourceManager.GetString("Polygon_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Points of the polygon.
        /// </summary>
        internal static string Polygon_Points {
            get {
                return ResourceManager.GetString("Polygon_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Color of the text.
        /// </summary>
        internal static string Text_Color {
            get {
                return ResourceManager.GetString("Text_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font of the text.  Only the family, size, bold, italic, underline, and strikethrough options are honored..
        /// </summary>
        internal static string Text_Font {
            get {
                return ResourceManager.GetString("Text_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Location of the text.
        /// </summary>
        internal static string Text_Location {
            get {
                return ResourceManager.GetString("Text_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the text.
        /// </summary>
        internal static string Text_Value {
            get {
                return ResourceManager.GetString("Text_Value", resourceCulture);
            }
        }
    }
}
