//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RdlReader.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RdlReader.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RDL Reader displays reports defined using the Report Definition Language Specification.
        ///Copyright (C) 2004-2008  fyiReporting Software, LLC
        ///Copyright (C) 2012 Peter Gill &lt;peter@majorsilence.com&gt;
        ///
        ///This file is part of the My-FyiReporting RDL project.
        ///	
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        ///you may not use this file except in compliance with the License.
        ///You may obtain a copy of the License at
        ///
        ///    http://www.apache.org/licenses/LICENSE-2.0
        ///
        ///Unless required by applicable  [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string DialogAbout_About {
            get {
                return ResourceManager.GetString("DialogAbout_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exception.
        /// </summary>
        public static string DialogAbout_ShowD_Exception {
            get {
                return ResourceManager.GetString("DialogAbout_ShowD_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version {0}.
        /// </summary>
        public static string DialogAbout_Version {
            get {
                return ResourceManager.GetString("DialogAbout_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RDL files (*.rdl)|*.rdl|Encrypted RDL files (*.encrypted)|*.encrypted|All files (*.*)|*.*.
        /// </summary>
        public static string RdlReader_menuFileOpen_Click_Filter {
            get {
                return ResourceManager.GetString("RdlReader_menuFileOpen_Click_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PDF files (*.pdf)|*.pdf|XML files (*.xml)|*.xml|HTML files (*.html)|*.html|CSV files (*.csv)|*.csv|RTF files (*.rtf)|*.rtf|TIF files (*.tif)|*.tif|Excel 2007 Table Only (*.xlsx)|*.xlsx|Excel 2007 (*.xlsx)|*.xlsx|MHT files (*.mht)|*.mht.
        /// </summary>
        public static string RdlReader_menuFileSaveAs_Click_FilesFilter {
            get {
                return ResourceManager.GetString("RdlReader_menuFileSaveAs_Click_FilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} is not a valid file type.  File extension must be PDF, XML, HTML, CSV, MHT, RTF, TIF, XLSX..
        /// </summary>
        public static string RdlReader_SaveG_NotValidFileType {
            get {
                return ResourceManager.GetString("RdlReader_SaveG_NotValidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save As Error.
        /// </summary>
        public static string RdlReader_SaveG_SaveAsError {
            get {
                return ResourceManager.GetString("RdlReader_SaveG_SaveAsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My-FyiReporting.
        /// </summary>
        public static string RdlReader_Show_MyFyiReporting {
            get {
                return ResourceManager.GetString("RdlReader_Show_MyFyiReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print error: .
        /// </summary>
        public static string RdlReader_ShowC_PrintError {
            get {
                return ResourceManager.GetString("RdlReader_ShowC_PrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can only print one file at a time..
        /// </summary>
        public static string RdlReader_ShowC_PrintOneFile {
            get {
                return ResourceManager.GetString("RdlReader_ShowC_PrintOneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The specified report [ {0} ] could not be loaded..
        /// </summary>
        public static string RdlReader_ShowD_ReportNotLoaded {
            get {
                return ResourceManager.GetString("RdlReader_ShowD_ReportNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export.
        /// </summary>
        public static string RdlReader_ShowF_Export {
            get {
                return ResourceManager.GetString("RdlReader_ShowF_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to save colors in TIF file?.
        /// </summary>
        public static string RdlReader_ShowF_WantSaveColorsInTIF {
            get {
                return ResourceManager.GetString("RdlReader_ShowF_WantSaveColorsInTIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Magnification level is an invalid number..
        /// </summary>
        public static string ZoomTo_ShowI_MagnificationLevelInvalid {
            get {
                return ResourceManager.GetString("ZoomTo_ShowI_MagnificationLevelInvalid", resourceCulture);
            }
        }
    }
}
