//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RdlReader.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RdlReader.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDL Reader displays reports defined using the Report Definition Language Specification.
        ///Copyright (C) 2004-2008  fyiReporting Software, LLC
        ///Copyright (C) 2012 Peter Gill &lt;peter@majorsilence.com&gt;
        ///
        ///This file is part of the My-FyiReporting RDL project.
        ///	
        ///Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        ///you may not use this file except in compliance with the License.
        ///You may obtain a copy of the License at
        ///
        ///    http://www.apache.org/licenses/LICENSE-2.0
        ///
        ///Unless required by applicable  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DialogAbout_About {
            get {
                return ResourceManager.GetString("DialogAbout_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string DialogAbout_ShowD_Exception {
            get {
                return ResourceManager.GetString("DialogAbout_ShowD_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string DialogAbout_Version {
            get {
                return ResourceManager.GetString("DialogAbout_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RDL files (*.rdl)|*.rdl|Encrypted RDL files (*.encrypted)|*.encrypted|All files (*.*)|*.*.
        /// </summary>
        internal static string RdlReader_menuFileOpen_Click_Filter {
            get {
                return ResourceManager.GetString("RdlReader_menuFileOpen_Click_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF files (*.pdf)|*.pdf|XML files (*.xml)|*.xml|HTML files (*.html)|*.html|CSV files (*.csv)|*.csv|RTF files (*.rtf)|*.rtf|TIF files (*.tif)|*.tif|Excel files (*.xlsx)|*.xlsx|MHT files (*.mht)|*.mht.
        /// </summary>
        internal static string RdlReader_menuFileSaveAs_Click_FilesFilter {
            get {
                return ResourceManager.GetString("RdlReader_menuFileSaveAs_Click_FilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid file type.  File extension must be PDF, XML, HTML, CSV, MHT, RTF, TIF, XLSX..
        /// </summary>
        internal static string RdlReader_SaveG_NotValidFileType {
            get {
                return ResourceManager.GetString("RdlReader_SaveG_NotValidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As Error.
        /// </summary>
        internal static string RdlReader_SaveG_SaveAsError {
            get {
                return ResourceManager.GetString("RdlReader_SaveG_SaveAsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My-FyiReporting.
        /// </summary>
        internal static string RdlReader_Show_MyFyiReporting {
            get {
                return ResourceManager.GetString("RdlReader_Show_MyFyiReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print error: .
        /// </summary>
        internal static string RdlReader_ShowC_PrintError {
            get {
                return ResourceManager.GetString("RdlReader_ShowC_PrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only print one file at a time..
        /// </summary>
        internal static string RdlReader_ShowC_PrintOneFile {
            get {
                return ResourceManager.GetString("RdlReader_ShowC_PrintOneFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified report [ {0} ] could not be loaded..
        /// </summary>
        internal static string RdlReader_ShowD_ReportNotLoaded {
            get {
                return ResourceManager.GetString("RdlReader_ShowD_ReportNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string RdlReader_ShowF_Export {
            get {
                return ResourceManager.GetString("RdlReader_ShowF_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save colors in TIF file?.
        /// </summary>
        internal static string RdlReader_ShowF_WantSaveColorsInTIF {
            get {
                return ResourceManager.GetString("RdlReader_ShowF_WantSaveColorsInTIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnification level is an invalid number..
        /// </summary>
        internal static string ZoomTo_ShowI_MagnificationLevelInvalid {
            get {
                return ResourceManager.GetString("ZoomTo_ShowI_MagnificationLevelInvalid", resourceCulture);
            }
        }
    }
}
