//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyiReporting.RdlDesign.RdlProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fyiReporting.RdlDesign.RdlProperties.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color.
        /// </summary>
        internal static string Appearance_Color {
            get {
                return ResourceManager.GetString("Appearance_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is either written left-to-right (LTR) or right-to-left (RTL)..
        /// </summary>
        internal static string Appearance_Direction {
            get {
                return ResourceManager.GetString("Appearance_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontFamily is the name of the font family.  Not all renderers support all fonts..
        /// </summary>
        internal static string Appearance_FontFamily {
            get {
                return ResourceManager.GetString("Appearance_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size controls the text size..
        /// </summary>
        internal static string Appearance_FontSize {
            get {
                return ResourceManager.GetString("Appearance_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontStyle determines if font is italicized..
        /// </summary>
        internal static string Appearance_FontStyle {
            get {
                return ResourceManager.GetString("Appearance_FontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontWeight controls the boldness of the font..
        /// </summary>
        internal static string Appearance_FontWeight {
            get {
                return ResourceManager.GetString("Appearance_FontWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depending on type the value can be formatted..
        /// </summary>
        internal static string Appearance_Format {
            get {
                return ResourceManager.GetString("Appearance_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal alignment.
        /// </summary>
        internal static string Appearance_TextAlign {
            get {
                return ResourceManager.GetString("Appearance_TextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextDecoration controls underline, overline, and linethrough.  Not all renderers support all options..
        /// </summary>
        internal static string Appearance_TextDecoration {
            get {
                return ResourceManager.GetString("Appearance_TextDecoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical alignment.
        /// </summary>
        internal static string Appearance_VerticalAlign {
            get {
                return ResourceManager.GetString("Appearance_VerticalAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is either written horizontally (lr-tb) or vertically (tb-rl)..
        /// </summary>
        internal static string Appearance_WritingMode {
            get {
                return ResourceManager.GetString("Appearance_WritingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color..
        /// </summary>
        internal static string Background_Color {
            get {
                return ResourceManager.GetString("Background_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End color when gradient type is not None..
        /// </summary>
        internal static string Background_EndColor {
            get {
                return ResourceManager.GetString("Background_EndColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of background gradient..
        /// </summary>
        internal static string Background_GradientType {
            get {
                return ResourceManager.GetString("Background_GradientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image to place in the background of the report item.
        /// </summary>
        internal static string Background_Image {
            get {
                return ResourceManager.GetString("Background_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Source is Database MIMEType describes the type of image..
        /// </summary>
        internal static string BackgroundImage_MIMEType {
            get {
                return ResourceManager.GetString("BackgroundImage_MIMEType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls repeating of the background image to fill space..
        /// </summary>
        internal static string BackgroundImage_Repeat {
            get {
                return ResourceManager.GetString("BackgroundImage_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image Source: None, External, Embedded, Database..
        /// </summary>
        internal static string BackgroundImage_Source {
            get {
                return ResourceManager.GetString("BackgroundImage_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value depends upon the source of the image..
        /// </summary>
        internal static string BackgroundImage_Value {
            get {
                return ResourceManager.GetString("BackgroundImage_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines a hyperlink, bookmark link, or drillthrough action for the report item..
        /// </summary>
        internal static string Base_Action {
            get {
                return ResourceManager.GetString("Base_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the background expressions..
        /// </summary>
        internal static string Base_Background {
            get {
                return ResourceManager.GetString("Base_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In PDFs, bookmarks are created for each instance of the report item.  For example, putting a bookmark on a report item in a group header will generate a list of the groups in the report..
        /// </summary>
        internal static string Base_Bookmark {
            get {
                return ResourceManager.GetString("Base_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the border of the report item..
        /// </summary>
        internal static string Base_Border {
            get {
                return ResourceManager.GetString("Base_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report item can span multiple columns..
        /// </summary>
        internal static string Base_ColumnSpan {
            get {
                return ResourceManager.GetString("Base_ColumnSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name to use for the element or attribute when exporting to XML..
        /// </summary>
        internal static string Base_DataElementName {
            get {
                return ResourceManager.GetString("Base_DataElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When rendering XML determines how or whether the item appears in the XML..
        /// </summary>
        internal static string Base_DataElementOutput {
            get {
                return ResourceManager.GetString("Base_DataElementOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of the report item..
        /// </summary>
        internal static string Base_Location {
            get {
                return ResourceManager.GetString("Base_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix report item properties..
        /// </summary>
        internal static string Base_Matrix {
            get {
                return ResourceManager.GetString("Base_Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique name of the report item..
        /// </summary>
        internal static string Base_Name {
            get {
                return ResourceManager.GetString("Base_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls the padding expressions..
        /// </summary>
        internal static string Base_Padding {
            get {
                return ResourceManager.GetString("Base_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height and width of the report item..
        /// </summary>
        internal static string Base_Size {
            get {
                return ResourceManager.GetString("Base_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table report item properties..
        /// </summary>
        internal static string Base_Table {
            get {
                return ResourceManager.GetString("Base_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ToolTip provides a label that can be used by a renderer.  For example, the Viewer and PDF renderers use this to popup the specified text when the mouse is over the report item..
        /// </summary>
        internal static string Base_ToolTip {
            get {
                return ResourceManager.GetString("Base_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the visibility of the item..
        /// </summary>
        internal static string Base_Visibility {
            get {
                return ResourceManager.GetString("Base_Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing order of the report item..
        /// </summary>
        internal static string Base_ZIndex {
            get {
                return ResourceManager.GetString("Base_ZIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryAxis defines the category (X) axis..
        /// </summary>
        internal static string Chart_CategoryAxis {
            get {
                return ResourceManager.GetString("Chart_CategoryAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties controlling the display of the chart data..
        /// </summary>
        internal static string Chart_ChartData {
            get {
                return ResourceManager.GetString("Chart_ChartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Legend..
        /// </summary>
        internal static string Chart_Legend {
            get {
                return ResourceManager.GetString("Chart_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color palette for the chart..
        /// </summary>
        internal static string Chart_Palette {
            get {
                return ResourceManager.GetString("Chart_Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage width for bars and columns..
        /// </summary>
        internal static string Chart_PointWidth {
            get {
                return ResourceManager.GetString("Chart_PointWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Title..
        /// </summary>
        internal static string Chart_Title {
            get {
                return ResourceManager.GetString("Chart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of the chart..
        /// </summary>
        internal static string Chart_Type {
            get {
                return ResourceManager.GetString("Chart_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueAxis defines the data (Y) axis..
        /// </summary>
        internal static string Chart_ValueAxis {
            get {
                return ResourceManager.GetString("Chart_ValueAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties controlling the display of an axis..
        /// </summary>
        internal static string ChartAxis {
            get {
                return ResourceManager.GetString("ChartAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font, color, alignment, ... of the axis..
        /// </summary>
        internal static string ChartAxis_Appearance {
            get {
                return ResourceManager.GetString("ChartAxis_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background of the axis..
        /// </summary>
        internal static string ChartAxis_Background {
            get {
                return ResourceManager.GetString("ChartAxis_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border properties of the axis..
        /// </summary>
        internal static string ChartAxis_Border {
            get {
                return ResourceManager.GetString("ChartAxis_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value at which to cross the other axis..
        /// </summary>
        internal static string ChartAxis_CrossAt {
            get {
                return ResourceManager.GetString("ChartAxis_CrossAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When true strip lines are drawn every other grid line..
        /// </summary>
        internal static string ChartAxis_Interlaced {
            get {
                return ResourceManager.GetString("ChartAxis_Interlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar.
        /// </summary>
        internal static string ChartAxis_LogScale {
            get {
                return ResourceManager.GetString("ChartAxis_LogScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Grid Lines properties.
        /// </summary>
        internal static string ChartAxis_MajorGridLines {
            get {
                return ResourceManager.GetString("ChartAxis_MajorGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit for major gridlines and tickmarks; omit for autodivision..
        /// </summary>
        internal static string ChartAxis_MajorInterval {
            get {
                return ResourceManager.GetString("ChartAxis_MajorInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major tick marks..
        /// </summary>
        internal static string ChartAxis_MajorTickMarks {
            get {
                return ResourceManager.GetString("ChartAxis_MajorTickMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there axis margin?.
        /// </summary>
        internal static string ChartAxis_Margin {
            get {
                return ResourceManager.GetString("ChartAxis_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum value for the axis.  When omitted axis autoscales..
        /// </summary>
        internal static string ChartAxis_Max {
            get {
                return ResourceManager.GetString("ChartAxis_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value for the axis.  When omitted axis autoscales..
        /// </summary>
        internal static string ChartAxis_Min {
            get {
                return ResourceManager.GetString("ChartAxis_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Grid Lines properties.
        /// </summary>
        internal static string ChartAxis_MinorGridLines {
            get {
                return ResourceManager.GetString("ChartAxis_MinorGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit for minor gridlines and tickmarks; omit for autodivision..
        /// </summary>
        internal static string ChartAxis_MinorInterval {
            get {
                return ResourceManager.GetString("ChartAxis_MinorInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor tick marks..
        /// </summary>
        internal static string ChartAxis_MinorTickMarks {
            get {
                return ResourceManager.GetString("ChartAxis_MinorTickMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding properties of the axis..
        /// </summary>
        internal static string ChartAxis_Padding {
            get {
                return ResourceManager.GetString("ChartAxis_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should axis be plotted normally (false) or should the direction be reversed?.
        /// </summary>
        internal static string ChartAxis_Reverse {
            get {
                return ResourceManager.GetString("ChartAxis_Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar.
        /// </summary>
        internal static string ChartAxis_Scalar {
            get {
                return ResourceManager.GetString("ChartAxis_Scalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title for the axis.
        /// </summary>
        internal static string ChartAxis_Title {
            get {
                return ResourceManager.GetString("ChartAxis_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the axis visible?.
        /// </summary>
        internal static string ChartAxis_Visible {
            get {
                return ResourceManager.GetString("ChartAxis_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties controlling the display of the chart data..
        /// </summary>
        internal static string ChartData {
            get {
                return ResourceManager.GetString("ChartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression that is to be charted..
        /// </summary>
        internal static string ChartData_DataValue {
            get {
                return ResourceManager.GetString("ChartData_DataValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Coordinate for Scatter and Bubble charts..
        /// </summary>
        internal static string ChartData_DataValue2 {
            get {
                return ResourceManager.GetString("ChartData_DataValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubble size in Bubble charts..
        /// </summary>
        internal static string ChartData_DataValue3 {
            get {
                return ResourceManager.GetString("ChartData_DataValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance of the label when visible..
        /// </summary>
        internal static string ChartData_LabelAppearance {
            get {
                return ResourceManager.GetString("ChartData_LabelAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should data label be displayed?.
        /// </summary>
        internal static string ChartData_LabelVisible {
            get {
                return ResourceManager.GetString("ChartData_LabelVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line color.
        /// </summary>
        internal static string ChartGridLines_Color {
            get {
                return ResourceManager.GetString("ChartGridLines_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line style: Dotted, Dashed or Solid.
        /// </summary>
        internal static string ChartGridLines_LineStyle {
            get {
                return ResourceManager.GetString("ChartGridLines_LineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines if grid lines are shown..
        /// </summary>
        internal static string ChartGridLines_ShowGridLines {
            get {
                return ResourceManager.GetString("ChartGridLines_ShowGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of line.
        /// </summary>
        internal static string ChartGridLines_Width {
            get {
                return ResourceManager.GetString("ChartGridLines_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties controlling the display of the chart legend..
        /// </summary>
        internal static string ChartLegend {
            get {
                return ResourceManager.GetString("ChartLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font, color, alignment, ... of the legend..
        /// </summary>
        internal static string ChartLegend_Appearance {
            get {
                return ResourceManager.GetString("ChartLegend_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background of the legend..
        /// </summary>
        internal static string ChartLegend_Background {
            get {
                return ResourceManager.GetString("ChartLegend_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border properties of the legend..
        /// </summary>
        internal static string ChartLegend_Border {
            get {
                return ResourceManager.GetString("ChartLegend_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw legend inside the plot area when true, otherwise outside..
        /// </summary>
        internal static string ChartLegend_InsidePlotArea {
            get {
                return ResourceManager.GetString("ChartLegend_InsidePlotArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout of the legend..
        /// </summary>
        internal static string ChartLegend_Layout {
            get {
                return ResourceManager.GetString("ChartLegend_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding properties of the legend..
        /// </summary>
        internal static string ChartLegend_Padding {
            get {
                return ResourceManager.GetString("ChartLegend_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position of the legend..
        /// </summary>
        internal static string ChartLegend_Position {
            get {
                return ResourceManager.GetString("ChartLegend_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the legend visible?.
        /// </summary>
        internal static string ChartLegend_Visible {
            get {
                return ResourceManager.GetString("ChartLegend_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties controlling the display of the chart title..
        /// </summary>
        internal static string ChartTitle {
            get {
                return ResourceManager.GetString("ChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font, color, alignment, ... of the caption..
        /// </summary>
        internal static string ChartTitle_Appearance {
            get {
                return ResourceManager.GetString("ChartTitle_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background of the caption..
        /// </summary>
        internal static string ChartTitle_Background {
            get {
                return ResourceManager.GetString("ChartTitle_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border properties of the caption..
        /// </summary>
        internal static string ChartTitle_Border {
            get {
                return ResourceManager.GetString("ChartTitle_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text of the title..
        /// </summary>
        internal static string ChartTitle_Caption {
            get {
                return ResourceManager.GetString("ChartTitle_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding properties of the caption..
        /// </summary>
        internal static string ChartTitle_Padding {
            get {
                return ResourceManager.GetString("ChartTitle_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font, color, alignment, ... of NoRows text..
        /// </summary>
        internal static string DataRegion_Appearance {
            get {
                return ResourceManager.GetString("DataRegion_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies which data set to use..
        /// </summary>
        internal static string DataRegion_DataSetName {
            get {
                return ResourceManager.GetString("DataRegion_DataSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters to apply to each row of data in data region..
        /// </summary>
        internal static string DataRegion_Filters {
            get {
                return ResourceManager.GetString("DataRegion_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep data region on one page if possible..
        /// </summary>
        internal static string DataRegion_KeepTogether {
            get {
                return ResourceManager.GetString("DataRegion_KeepTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message to display if no rows available..
        /// </summary>
        internal static string DataRegion_NoRows {
            get {
                return ResourceManager.GetString("DataRegion_NoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause a page break after rendering..
        /// </summary>
        internal static string DataRegion_PageBreakAtEnd {
            get {
                return ResourceManager.GetString("DataRegion_PageBreakAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause a page break before rendering..
        /// </summary>
        internal static string DataRegion_PageBreakAtStart {
            get {
                return ResourceManager.GetString("DataRegion_PageBreakAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image properties..
        /// </summary>
        internal static string Image_Image {
            get {
                return ResourceManager.GetString("Image_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When Source is Database MIMEType describes the type of image..
        /// </summary>
        internal static string ImageI_MIMEType {
            get {
                return ResourceManager.GetString("ImageI_MIMEType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines how image is sized when image doesn&apos;t match specified size..
        /// </summary>
        internal static string ImageI_Sizing {
            get {
                return ResourceManager.GetString("ImageI_Sizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Source:External, Embedded, Database..
        /// </summary>
        internal static string ImageI_Source {
            get {
                return ResourceManager.GetString("ImageI_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value depends upon the source of the image..
        /// </summary>
        internal static string ImageI_Value {
            get {
                return ResourceManager.GetString("ImageI_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines whether list instances appear in the XML..
        /// </summary>
        internal static string List_DataInstanceElementOutput {
            get {
                return ResourceManager.GetString("List_DataInstanceElementOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name to use for the data element for each instance of this list when exporting to XML..
        /// </summary>
        internal static string List_DataInstanceName {
            get {
                return ResourceManager.GetString("List_DataInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping data allows each repeated list region to represent a summarization of the rows in the group..
        /// </summary>
        internal static string List_Grouping {
            get {
                return ResourceManager.GetString("List_Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting controls the order of the repeated list regions..
        /// </summary>
        internal static string List_Sorting {
            get {
                return ResourceManager.GetString("List_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines if report will start a new page after the bottom of the rectangle..
        /// </summary>
        internal static string Rectangle_PageBreakAtEnd {
            get {
                return ResourceManager.GetString("Rectangle_PageBreakAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines if report will start a new page at the top of the rectangle..
        /// </summary>
        internal static string Rectangle_PageBreakAtStart {
            get {
                return ResourceManager.GetString("Rectangle_PageBreakAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The author of the report.
        /// </summary>
        internal static string Report_Author {
            get {
                return ResourceManager.GetString("Report_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of columns in the body region..
        /// </summary>
        internal static string Report_BodyColumns {
            get {
                return ResourceManager.GetString("Report_BodyColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing between columns..
        /// </summary>
        internal static string Report_BodyColumnSpacing {
            get {
                return ResourceManager.GetString("Report_BodyColumnSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height of the body region..
        /// </summary>
        internal static string Report_BodyHeight {
            get {
                return ResourceManager.GetString("Report_BodyHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic functions defined for use in the report..
        /// </summary>
        internal static string Report_Code {
            get {
                return ResourceManager.GetString("Report_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The top level element name used when rendering XML..
        /// </summary>
        internal static string Report_DataElementName {
            get {
                return ResourceManager.GetString("Report_DataElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element style is either Attribute or Element..
        /// </summary>
        internal static string Report_DataElementStyle {
            get {
                return ResourceManager.GetString("Report_DataElementStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema or namespace to specify when rendering XML..
        /// </summary>
        internal static string Report_DataSchema {
            get {
                return ResourceManager.GetString("Report_DataSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XSL file to use to transform XML after rendering..
        /// </summary>
        internal static string Report_DataTransform {
            get {
                return ResourceManager.GetString("Report_DataTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of the report.
        /// </summary>
        internal static string Report_Description {
            get {
                return ResourceManager.GetString("Report_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page margins for the report..
        /// </summary>
        internal static string Report_Margins {
            get {
                return ResourceManager.GetString("Report_Margins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules and instances of classes for use in the report..
        /// </summary>
        internal static string Report_ModulesClasses {
            get {
                return ResourceManager.GetString("Report_ModulesClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageFooter options for the report..
        /// </summary>
        internal static string Report_PageFooter {
            get {
                return ResourceManager.GetString("Report_PageFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageHeader options for the report..
        /// </summary>
        internal static string Report_PageHeader {
            get {
                return ResourceManager.GetString("Report_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The height of the page..
        /// </summary>
        internal static string Report_PageHeight {
            get {
                return ResourceManager.GetString("Report_PageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width of the page..
        /// </summary>
        internal static string Report_PageWidth {
            get {
                return ResourceManager.GetString("Report_PageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters defined in the report..
        /// </summary>
        internal static string Report_Parameters {
            get {
                return ResourceManager.GetString("Report_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width of the report..
        /// </summary>
        internal static string Report_Width {
            get {
                return ResourceManager.GetString("Report_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When true DataSource connections in subreport will reuse parent report connections when possible..
        /// </summary>
        internal static string Subreport_MergeTransactions {
            get {
                return ResourceManager.GetString("Subreport_MergeTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the subreport either a full path or a relative path..
        /// </summary>
        internal static string Subreport_NoRows {
            get {
                return ResourceManager.GetString("Subreport_NoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subreport parameter expressions..
        /// </summary>
        internal static string Subreport_Parameters {
            get {
                return ResourceManager.GetString("Subreport_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the subreport either a full path or a relative path..
        /// </summary>
        internal static string Subreport_ReportName {
            get {
                return ResourceManager.GetString("Subreport_ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font, color, alignment, ... of text..
        /// </summary>
        internal static string Textbox_Appearance {
            get {
                return ResourceManager.GetString("Textbox_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanGrow indicates the height of the Textbox can increase depending on its contents..
        /// </summary>
        internal static string Textbox_CanGrow {
            get {
                return ResourceManager.GetString("Textbox_CanGrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanShrink indicates the height of the Textbox can decrease depending on its contents..
        /// </summary>
        internal static string Textbox_CanShrink {
            get {
                return ResourceManager.GetString("Textbox_CanShrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether Textbox renders as an Attribute or an Element..
        /// </summary>
        internal static string Textbox_DataElementStyle {
            get {
                return ResourceManager.GetString("Textbox_DataElementStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To HideDuplicate values provide the scope (dataset or group) over which you want to hide the Textbox..
        /// </summary>
        internal static string Textbox_HideDuplicates {
            get {
                return ResourceManager.GetString("Textbox_HideDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the textbox..
        /// </summary>
        internal static string Textbox_Value {
            get {
                return ResourceManager.GetString("Textbox_Value", resourceCulture);
            }
        }
    }
}
