//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majorsilence.Reporting.RdlDesign.RdlProperties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fyiReporting.RdlDesign.RdlProperties.DisplayNames", typeof(DisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Appearance_Color {
            get {
                return ResourceManager.GetString("Appearance_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        internal static string Appearance_Direction {
            get {
                return ResourceManager.GetString("Appearance_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontFamily.
        /// </summary>
        internal static string Appearance_FontFamily {
            get {
                return ResourceManager.GetString("Appearance_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontSize.
        /// </summary>
        internal static string Appearance_FontSize {
            get {
                return ResourceManager.GetString("Appearance_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontStyle.
        /// </summary>
        internal static string Appearance_FontStyle {
            get {
                return ResourceManager.GetString("Appearance_FontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FontWeight.
        /// </summary>
        internal static string Appearance_FontWeight {
            get {
                return ResourceManager.GetString("Appearance_FontWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string Appearance_Format {
            get {
                return ResourceManager.GetString("Appearance_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextAlign.
        /// </summary>
        internal static string Appearance_TextAlign {
            get {
                return ResourceManager.GetString("Appearance_TextAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextDecoration.
        /// </summary>
        internal static string Appearance_TextDecoration {
            get {
                return ResourceManager.GetString("Appearance_TextDecoration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VerticalAlign.
        /// </summary>
        internal static string Appearance_VerticalAlign {
            get {
                return ResourceManager.GetString("Appearance_VerticalAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WritingMode.
        /// </summary>
        internal static string Appearance_WritingMode {
            get {
                return ResourceManager.GetString("Appearance_WritingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Background_Color {
            get {
                return ResourceManager.GetString("Background_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndColor.
        /// </summary>
        internal static string Background_EndColor {
            get {
                return ResourceManager.GetString("Background_EndColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GradientType.
        /// </summary>
        internal static string Background_GradientType {
            get {
                return ResourceManager.GetString("Background_GradientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Background_Image {
            get {
                return ResourceManager.GetString("Background_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIMEType.
        /// </summary>
        internal static string BackgroundImage_MIMEType {
            get {
                return ResourceManager.GetString("BackgroundImage_MIMEType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string BackgroundImage_Repeat {
            get {
                return ResourceManager.GetString("BackgroundImage_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string BackgroundImage_Source {
            get {
                return ResourceManager.GetString("BackgroundImage_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string BackgroundImage_Value {
            get {
                return ResourceManager.GetString("BackgroundImage_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Base_Action {
            get {
                return ResourceManager.GetString("Base_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string Base_Background {
            get {
                return ResourceManager.GetString("Base_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        internal static string Base_Bookmark {
            get {
                return ResourceManager.GetString("Base_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        internal static string Base_Border {
            get {
                return ResourceManager.GetString("Base_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnSpan.
        /// </summary>
        internal static string Base_ColumnSpan {
            get {
                return ResourceManager.GetString("Base_ColumnSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataElementName.
        /// </summary>
        internal static string Base_DataElementName {
            get {
                return ResourceManager.GetString("Base_DataElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataElementOutput.
        /// </summary>
        internal static string Base_DataElementOutput {
            get {
                return ResourceManager.GetString("Base_DataElementOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Base_Location {
            get {
                return ResourceManager.GetString("Base_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix.
        /// </summary>
        internal static string Base_Matrix {
            get {
                return ResourceManager.GetString("Base_Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Base_Name {
            get {
                return ResourceManager.GetString("Base_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        internal static string Base_Padding {
            get {
                return ResourceManager.GetString("Base_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Base_Size {
            get {
                return ResourceManager.GetString("Base_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Base_Table {
            get {
                return ResourceManager.GetString("Base_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip.
        /// </summary>
        internal static string Base_ToolTip {
            get {
                return ResourceManager.GetString("Base_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string Base_Visibility {
            get {
                return ResourceManager.GetString("Base_Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIndex.
        /// </summary>
        internal static string Base_ZIndex {
            get {
                return ResourceManager.GetString("Base_ZIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CategoryAxis.
        /// </summary>
        internal static string Chart_CategoryAxis {
            get {
                return ResourceManager.GetString("Chart_CategoryAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChartData.
        /// </summary>
        internal static string Chart_ChartData {
            get {
                return ResourceManager.GetString("Chart_ChartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        internal static string Chart_Legend {
            get {
                return ResourceManager.GetString("Chart_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette.
        /// </summary>
        internal static string Chart_Palette {
            get {
                return ResourceManager.GetString("Chart_Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PointWidth.
        /// </summary>
        internal static string Chart_PointWidth {
            get {
                return ResourceManager.GetString("Chart_PointWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Chart_Title {
            get {
                return ResourceManager.GetString("Chart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Chart_Type {
            get {
                return ResourceManager.GetString("Chart_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValueAxis.
        /// </summary>
        internal static string Chart_ValueAxis {
            get {
                return ResourceManager.GetString("Chart_ValueAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string ChartAxis_Appearance {
            get {
                return ResourceManager.GetString("ChartAxis_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string ChartAxis_Background {
            get {
                return ResourceManager.GetString("ChartAxis_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        internal static string ChartAxis_Border {
            get {
                return ResourceManager.GetString("ChartAxis_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossAt.
        /// </summary>
        internal static string ChartAxis_CrossAt {
            get {
                return ResourceManager.GetString("ChartAxis_CrossAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlaced.
        /// </summary>
        internal static string ChartAxis_Interlaced {
            get {
                return ResourceManager.GetString("ChartAxis_Interlaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogScale.
        /// </summary>
        internal static string ChartAxis_LogScale {
            get {
                return ResourceManager.GetString("ChartAxis_LogScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MajorGridLines.
        /// </summary>
        internal static string ChartAxis_MajorGridLines {
            get {
                return ResourceManager.GetString("ChartAxis_MajorGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MajorInterval.
        /// </summary>
        internal static string ChartAxis_MajorInterval {
            get {
                return ResourceManager.GetString("ChartAxis_MajorInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MajorTickMarks.
        /// </summary>
        internal static string ChartAxis_MajorTickMarks {
            get {
                return ResourceManager.GetString("ChartAxis_MajorTickMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        internal static string ChartAxis_Margin {
            get {
                return ResourceManager.GetString("ChartAxis_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string ChartAxis_Max {
            get {
                return ResourceManager.GetString("ChartAxis_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string ChartAxis_Min {
            get {
                return ResourceManager.GetString("ChartAxis_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinorGridLines.
        /// </summary>
        internal static string ChartAxis_MinorGridLines {
            get {
                return ResourceManager.GetString("ChartAxis_MinorGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinorInterval.
        /// </summary>
        internal static string ChartAxis_MinorInterval {
            get {
                return ResourceManager.GetString("ChartAxis_MinorInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinorTickMarks.
        /// </summary>
        internal static string ChartAxis_MinorTickMarks {
            get {
                return ResourceManager.GetString("ChartAxis_MinorTickMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        internal static string ChartAxis_Padding {
            get {
                return ResourceManager.GetString("ChartAxis_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        internal static string ChartAxis_Reverse {
            get {
                return ResourceManager.GetString("ChartAxis_Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalar.
        /// </summary>
        internal static string ChartAxis_Scalar {
            get {
                return ResourceManager.GetString("ChartAxis_Scalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ChartAxis_Title {
            get {
                return ResourceManager.GetString("ChartAxis_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string ChartAxis_Visible {
            get {
                return ResourceManager.GetString("ChartAxis_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataValue.
        /// </summary>
        internal static string ChartData_DataValue {
            get {
                return ResourceManager.GetString("ChartData_DataValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataValue2.
        /// </summary>
        internal static string ChartData_DataValue2 {
            get {
                return ResourceManager.GetString("ChartData_DataValue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataValue3.
        /// </summary>
        internal static string ChartData_DataValue3 {
            get {
                return ResourceManager.GetString("ChartData_DataValue3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelAppearance.
        /// </summary>
        internal static string ChartData_LabelAppearance {
            get {
                return ResourceManager.GetString("ChartData_LabelAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LabelVisible.
        /// </summary>
        internal static string ChartData_LabelVisible {
            get {
                return ResourceManager.GetString("ChartData_LabelVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string ChartGridLines_Color {
            get {
                return ResourceManager.GetString("ChartGridLines_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineStyle.
        /// </summary>
        internal static string ChartGridLines_LineStyle {
            get {
                return ResourceManager.GetString("ChartGridLines_LineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowGridLines.
        /// </summary>
        internal static string ChartGridLines_ShowGridLines {
            get {
                return ResourceManager.GetString("ChartGridLines_ShowGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string ChartGridLines_Width {
            get {
                return ResourceManager.GetString("ChartGridLines_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string ChartLegend_Appearance {
            get {
                return ResourceManager.GetString("ChartLegend_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string ChartLegend_Background {
            get {
                return ResourceManager.GetString("ChartLegend_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        internal static string ChartLegend_Border {
            get {
                return ResourceManager.GetString("ChartLegend_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsidePlotArea.
        /// </summary>
        internal static string ChartLegend_InsidePlotArea {
            get {
                return ResourceManager.GetString("ChartLegend_InsidePlotArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string ChartLegend_Layout {
            get {
                return ResourceManager.GetString("ChartLegend_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        internal static string ChartLegend_Padding {
            get {
                return ResourceManager.GetString("ChartLegend_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string ChartLegend_Position {
            get {
                return ResourceManager.GetString("ChartLegend_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string ChartLegend_Visible {
            get {
                return ResourceManager.GetString("ChartLegend_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string ChartTitle_Appearance {
            get {
                return ResourceManager.GetString("ChartTitle_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string ChartTitle_Background {
            get {
                return ResourceManager.GetString("ChartTitle_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        internal static string ChartTitle_Border {
            get {
                return ResourceManager.GetString("ChartTitle_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string ChartTitle_Caption {
            get {
                return ResourceManager.GetString("ChartTitle_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        internal static string ChartTitle_Padding {
            get {
                return ResourceManager.GetString("ChartTitle_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string DataRegion_Appearance {
            get {
                return ResourceManager.GetString("DataRegion_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSetName.
        /// </summary>
        internal static string DataRegion_DataSetName {
            get {
                return ResourceManager.GetString("DataRegion_DataSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string DataRegion_Filters {
            get {
                return ResourceManager.GetString("DataRegion_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeepTogether.
        /// </summary>
        internal static string DataRegion_KeepTogether {
            get {
                return ResourceManager.GetString("DataRegion_KeepTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoRows.
        /// </summary>
        internal static string DataRegion_NoRows {
            get {
                return ResourceManager.GetString("DataRegion_NoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageBreakAtEnd.
        /// </summary>
        internal static string DataRegion_PageBreakAtEnd {
            get {
                return ResourceManager.GetString("DataRegion_PageBreakAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageBreakAtStart.
        /// </summary>
        internal static string DataRegion_PageBreakAtStart {
            get {
                return ResourceManager.GetString("DataRegion_PageBreakAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image_Image {
            get {
                return ResourceManager.GetString("Image_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIMEType.
        /// </summary>
        internal static string ImageI_MIMEType {
            get {
                return ResourceManager.GetString("ImageI_MIMEType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizing.
        /// </summary>
        internal static string ImageI_Sizing {
            get {
                return ResourceManager.GetString("ImageI_Sizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string ImageI_Source {
            get {
                return ResourceManager.GetString("ImageI_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ImageI_Value {
            get {
                return ResourceManager.GetString("ImageI_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataInstanceElementOutput.
        /// </summary>
        internal static string List_DataInstanceElementOutput {
            get {
                return ResourceManager.GetString("List_DataInstanceElementOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataInstanceName.
        /// </summary>
        internal static string List_DataInstanceName {
            get {
                return ResourceManager.GetString("List_DataInstanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        internal static string List_Grouping {
            get {
                return ResourceManager.GetString("List_Grouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        internal static string List_Sorting {
            get {
                return ResourceManager.GetString("List_Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Location_Left {
            get {
                return ResourceManager.GetString("Location_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Location_Top {
            get {
                return ResourceManager.GetString("Location_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Margin_Bottom {
            get {
                return ResourceManager.GetString("Margin_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Margin_Left {
            get {
                return ResourceManager.GetString("Margin_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Margin_Right {
            get {
                return ResourceManager.GetString("Margin_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Margin_Top {
            get {
                return ResourceManager.GetString("Margin_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Padding_Bottom {
            get {
                return ResourceManager.GetString("Padding_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Padding_Left {
            get {
                return ResourceManager.GetString("Padding_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Padding_Right {
            get {
                return ResourceManager.GetString("Padding_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Padding_Top {
            get {
                return ResourceManager.GetString("Padding_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string PrintFirstLast_Height {
            get {
                return ResourceManager.GetString("PrintFirstLast_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintOnFirstPage.
        /// </summary>
        internal static string PrintFirstLast_PrintOnFirstPage {
            get {
                return ResourceManager.GetString("PrintFirstLast_PrintOnFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintOnLastPage.
        /// </summary>
        internal static string PrintFirstLast_PrintOnLastPage {
            get {
                return ResourceManager.GetString("PrintFirstLast_PrintOnLastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageBreakAtEnd.
        /// </summary>
        internal static string Rectangle_PageBreakAtEnd {
            get {
                return ResourceManager.GetString("Rectangle_PageBreakAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageBreakAtStart.
        /// </summary>
        internal static string Rectangle_PageBreakAtStart {
            get {
                return ResourceManager.GetString("Rectangle_PageBreakAtStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string Report_Author {
            get {
                return ResourceManager.GetString("Report_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BodyColumns.
        /// </summary>
        internal static string Report_BodyColumns {
            get {
                return ResourceManager.GetString("Report_BodyColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BodyColumnSpacing.
        /// </summary>
        internal static string Report_BodyColumnSpacing {
            get {
                return ResourceManager.GetString("Report_BodyColumnSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BodyHeight.
        /// </summary>
        internal static string Report_BodyHeight {
            get {
                return ResourceManager.GetString("Report_BodyHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Report_Code {
            get {
                return ResourceManager.GetString("Report_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataElementName.
        /// </summary>
        internal static string Report_DataElementName {
            get {
                return ResourceManager.GetString("Report_DataElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataElementStyle.
        /// </summary>
        internal static string Report_DataElementStyle {
            get {
                return ResourceManager.GetString("Report_DataElementStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataSchema.
        /// </summary>
        internal static string Report_DataSchema {
            get {
                return ResourceManager.GetString("Report_DataSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTransform.
        /// </summary>
        internal static string Report_DataTransform {
            get {
                return ResourceManager.GetString("Report_DataTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Report_Description {
            get {
                return ResourceManager.GetString("Report_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Margins.
        /// </summary>
        internal static string Report_Margins {
            get {
                return ResourceManager.GetString("Report_Margins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModulesClasses.
        /// </summary>
        internal static string Report_ModulesClasses {
            get {
                return ResourceManager.GetString("Report_ModulesClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageFooter.
        /// </summary>
        internal static string Report_PageFooter {
            get {
                return ResourceManager.GetString("Report_PageFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageHeader.
        /// </summary>
        internal static string Report_PageHeader {
            get {
                return ResourceManager.GetString("Report_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageHeight.
        /// </summary>
        internal static string Report_PageHeight {
            get {
                return ResourceManager.GetString("Report_PageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageWidth.
        /// </summary>
        internal static string Report_PageWidth {
            get {
                return ResourceManager.GetString("Report_PageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string Report_Parameters {
            get {
                return ResourceManager.GetString("Report_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Report_Width {
            get {
                return ResourceManager.GetString("Report_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Size_Height {
            get {
                return ResourceManager.GetString("Size_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Size_Width {
            get {
                return ResourceManager.GetString("Size_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MergeTransactions.
        /// </summary>
        internal static string Subreport_MergeTransactions {
            get {
                return ResourceManager.GetString("Subreport_MergeTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoRows.
        /// </summary>
        internal static string Subreport_NoRows {
            get {
                return ResourceManager.GetString("Subreport_NoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        internal static string Subreport_Parameters {
            get {
                return ResourceManager.GetString("Subreport_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportName.
        /// </summary>
        internal static string Subreport_ReportName {
            get {
                return ResourceManager.GetString("Subreport_ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string Textbox_Appearance {
            get {
                return ResourceManager.GetString("Textbox_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanGrow.
        /// </summary>
        internal static string Textbox_CanGrow {
            get {
                return ResourceManager.GetString("Textbox_CanGrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanShrink.
        /// </summary>
        internal static string Textbox_CanShrink {
            get {
                return ResourceManager.GetString("Textbox_CanShrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataElementStyle.
        /// </summary>
        internal static string Textbox_DataElementStyle {
            get {
                return ResourceManager.GetString("Textbox_DataElementStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HideDuplicates.
        /// </summary>
        internal static string Textbox_HideDuplicates {
            get {
                return ResourceManager.GetString("Textbox_HideDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Textbox_Value {
            get {
                return ResourceManager.GetString("Textbox_Value", resourceCulture);
            }
        }
    }
}
