// This file has been generated by the GUI designer. Do not modify.

using Gtk;

namespace Majorsilence.Reporting.RdlGtk3
{
    public partial class ParameterPrompt : Dialog
    {
        private Button buttonCancel;
        private Button buttonOk;
        private HBox hbox3;
        private Label label2;
        private Entry TextBoxParameters;

        protected virtual void Build()
        {
            // Widget Majorsilence.Reporting.RdlGtkViewer.ParameterPrompt
            Name = "fyiReporting.RdlGtk3.ParameterPrompt";
            WindowPosition = WindowPosition.Center;

            // Internal child Majorsilence.Reporting.RdlGtkViewer.ParameterPrompt.VBox
#pragma warning disable CS0612 // Type or member is obsolete
            VBox vbox = new();
#pragma warning restore CS0612 // Type or member is obsolete
            vbox.Name = "dialog1_VBox";
            vbox.BorderWidth = 2;

            // Container child dialog1_VBox.Gtk.Box+BoxChild
#pragma warning disable CS0612 // Type or member is obsolete
            hbox3 = new HBox();
#pragma warning restore CS0612 // Type or member is obsolete
            hbox3.Name = "hbox3";
            hbox3.Spacing = 6;

            // Container child hbox3.Gtk.Box+BoxChild
            label2 = new Label();
            label2.Name = "label2";
            label2.LabelProp = "Enter Parameters";
            hbox3.PackStart(label2, false, false, 0);

            // Container child hbox3.Gtk.Box+BoxChild
            TextBoxParameters = new Entry();
            TextBoxParameters.CanFocus = true;
            TextBoxParameters.Name = "TextBoxParameters";
            TextBoxParameters.IsEditable = true;
            TextBoxParameters.InvisibleChar = '•';
            hbox3.PackStart(TextBoxParameters, false, false, 0);

            vbox.PackStart(hbox3, false, false, 0);

            // Internal child Majorsilence.Reporting.RdlGtkViewer.ParameterPrompt.ActionArea
#pragma warning disable CS0612 // Type or member is obsolete
            HButtonBox actionArea = new();
#pragma warning restore CS0612 // Type or member is obsolete
            actionArea.Name = "dialog1_ActionArea";
            actionArea.Spacing = 10;
            actionArea.BorderWidth = 5;
            actionArea.LayoutStyle = ButtonBoxStyle.End;

            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            buttonCancel = new Button();
            buttonCancel.CanDefault = true;
            buttonCancel.CanFocus = true;
            buttonCancel.Name = "buttonCancel";
#pragma warning disable CS0612 // Type or member is obsolete
            buttonCancel.UseStock = true;
#pragma warning restore CS0612 // Type or member is obsolete
            buttonCancel.UseUnderline = true;
            buttonCancel.Label = "gtk-cancel";
            actionArea.PackStart(buttonCancel, false, false, 0);

            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            buttonOk = new Button();
            buttonOk.CanDefault = true;
            buttonOk.CanFocus = true;
            buttonOk.Name = "buttonOk";
#pragma warning disable CS0612 // Type or member is obsolete
            buttonOk.UseStock = true;
#pragma warning restore CS0612 // Type or member is obsolete
            buttonOk.UseUnderline = true;
            buttonOk.Label = "gtk-ok";
            actionArea.PackStart(buttonOk, false, false, 0);

            vbox.PackStart(actionArea, false, false, 0);

            Add(vbox);

            DefaultWidth = 400;
            DefaultHeight = 237;
            ShowAll();
        }
    }
}