
// This file has been generated by the GUI designer. Do not modify.
namespace fyiReporting.RdlGtk3
{
    public partial class MainWindow
    {
        private global::Gtk.Box vbox1;
        private global::Gtk.Box hbox1;
        private global::Gtk.Button SaveButton;
        private global::Gtk.Button PrintButton;
        private global::Gtk.Button FirstPageButton;
        private global::Gtk.Button PreviousButton;
        private global::Gtk.Button NextButton;
        private global::Gtk.Button LastPageButton;
        private global::Gtk.SpinButton CurrentPage;
        private global::Gtk.Label PageCountLabel;
        private global::Gtk.ScrolledWindow scrolledwindow1;
        private global::Gtk.Box vboxImages;

        private Gtk.Table table1;
        private Gtk.MenuBar menubar1;
        private fyiReporting.RdlGtk3.ReportViewer reportviewer1;
        private Gtk.Toolbar toolbar;
        private Gtk.Box hboxHeader;
        private Gtk.Box vbox;
        private Gtk.Box hbox;
        private Gtk.Box vboxParameters;
        private Gtk.Paned hpanedReport;
        private Gtk.ScrolledWindow scrolledwindowPages;
        private Gtk.Viewport GtkViewport;
        private Gtk.Box vboxPages;
        private Gtk.ScrolledWindow scrolledwindowErrors;
        private Gtk.TextView textviewErrors;


        protected virtual void Build()
        {
            // Container child RdlGtkViewer.RdlGtkViewer.Gtk.Container+ContainerChild
            this.vbox1 = new global::Gtk.Box(global::Gtk.Orientation.Vertical, 6);
            this.vbox1.Name = "vbox1";
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new global::Gtk.Box(global::Gtk.Orientation.Horizontal, 6);
            this.hbox1.Name = "hbox1";
            // Container child hbox1.Gtk.Box+BoxChild
            this.SaveButton = new global::Gtk.Button();
            this.SaveButton.CanFocus = true;
            this.SaveButton.Name = "SaveButton";
            this.SaveButton.UseStock = true;
            this.SaveButton.UseUnderline = true;
            this.SaveButton.Label = "gtk-save";
            this.hbox1.PackStart(this.SaveButton, false, false, 0);
            // Container child hbox1.Gtk.Box+BoxChild
            this.PrintButton = new global::Gtk.Button();
            this.PrintButton.CanFocus = true;
            this.PrintButton.Name = "PrintButton";
            this.PrintButton.UseStock = true;
            this.PrintButton.UseUnderline = true;
            this.PrintButton.Label = "gtk-print";
            this.hbox1.PackStart(this.PrintButton, false, false, 0);
            // Container child hbox1.Gtk.Box+BoxChild
            this.FirstPageButton = new global::Gtk.Button();
            this.FirstPageButton.CanFocus = true;
            this.FirstPageButton.Name = "FirstPageButton";
            this.FirstPageButton.UseStock = true;
            this.FirstPageButton.UseUnderline = true;
            this.FirstPageButton.Label = "gtk-goto-first";
            this.hbox1.PackStart(this.FirstPageButton, false, false, 0);
            // Container child hbox1.Gtk.Box+BoxChild
            this.PreviousButton = new global::Gtk.Button();
            this.PreviousButton.CanFocus = true;
            this.PreviousButton.Name = "PreviousButton";
            this.PreviousButton.UseStock = true;
            this.PreviousButton.UseUnderline = true;
            this.PreviousButton.Label = "gtk-go-back";
            this.hbox1.PackStart(this.PreviousButton, false, false, 0);
            // Container child hbox1.Gtk.Box+BoxChild
            this.NextButton = new global::Gtk.Button();
            this.NextButton.CanFocus = true;
            this.NextButton.Name = "NextButton";
            this.NextButton.UseStock = true;
            this.NextButton.UseUnderline = true;
            this.NextButton.Label = "gtk-go-forward";
            this.hbox1.PackStart(this.NextButton, false, false, 0);
            // Container child hbox1.Gtk.Box+BoxChild
            this.LastPageButton = new global::Gtk.Button();
            this.LastPageButton.CanFocus = true;
            this.LastPageButton.Name = "LastPageButton";
            this.LastPageButton.UseStock = true;
            this.LastPageButton.UseUnderline = true;
            this.LastPageButton.Label = "gtk-goto-last";
            this.hbox1.PackStart(this.LastPageButton, false, false, 0);
            // Container child hbox1.Gtk.Box+BoxChild
            this.CurrentPage = new global::Gtk.SpinButton(0, 999999, 1);
            this.CurrentPage.CanFocus = true;
            this.CurrentPage.Name = "CurrentPage";
            this.CurrentPage.Adjustment.PageIncrement = 10;
            this.CurrentPage.ClimbRate = 1;
            this.CurrentPage.Numeric = true;
            this.hbox1.PackStart(this.CurrentPage, false, false, 0);
            // Container child hbox1.Gtk.Box+BoxChild
            this.PageCountLabel = new global::Gtk.Label();
            this.PageCountLabel.Name = "PageCountLabel";
            this.hbox1.PackStart(this.PageCountLabel, false, false, 0);
            this.vbox1.PackStart(this.hbox1, false, false, 0);
            // Container child vbox1.Gtk.Box+BoxChild
            this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = global::Gtk.ShadowType.In;
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            global::Gtk.Viewport w10 = new global::Gtk.Viewport();
            w10.ShadowType = global::Gtk.ShadowType.None;
            // Container child GtkViewport.Gtk.Container+ContainerChild
            this.vboxImages = new global::Gtk.Box(global::Gtk.Orientation.Vertical, 6);
            this.vboxImages.Name = "vboxImages";
            w10.Add(this.vboxImages);
            this.scrolledwindow1.Add(w10);
            this.vbox1.PackStart(this.scrolledwindow1, true, true, 0);
 
            /*
            this.SaveButton.Clicked += new global::System.EventHandler(this.OnSaveButtonClicked);
            this.PrintButton.Clicked += new global::System.EventHandler(this.OnPrintButtonClicked);
            this.FirstPageButton.Clicked += new global::System.EventHandler(this.OnFirstPageButtonClicked);
            this.PreviousButton.Clicked += new global::System.EventHandler(this.OnPreviousButtonClicked);
            this.NextButton.Clicked += new global::System.EventHandler(this.OnNextButtonClicked);
            this.LastPageButton.Clicked += new global::System.EventHandler(this.OnLastPageButtonClicked);
            this.CurrentPage.ValueChanged += new global::System.EventHandler(this.OnCurrentPageValueChanged);
            */
        }
    }
}
