//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyiReporting.RdlViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fyiReporting.RdlViewer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minutes.
        /// </summary>
        internal static string DialogWait_Minutes {
            get {
                return ResourceManager.GetString("DialogWait_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Seconds.
        /// </summary>
        internal static string DialogWait_Seconds {
            get {
                return ResourceManager.GetString("DialogWait_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HyperLink Error.
        /// </summary>
        internal static string PageDrawing_OnMouseDown_HyperLinkError {
            get {
                return ResourceManager.GetString("PageDrawing_OnMouseDown_HyperLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to link to.
        /// </summary>
        internal static string PageDrawing_OnMouseDown_UnableLink {
            get {
                return ResourceManager.GetString("PageDrawing_OnMouseDown_UnableLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Incorrect Pass key entered..
        /// </summary>
        internal static string RdlViewer_doPossibleDecryption_Incorrect_Pass_key_entered_ {
            get {
                return ResourceManager.GetString("RdlViewer_doPossibleDecryption_Incorrect_Pass_key_entered_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report must be loaded prior to Rebuild being called..
        /// </summary>
        internal static string RdlViewer_Error_Report_must_be_loaded_prior_to_Rebuild_being_called {
            get {
                return ResourceManager.GetString("RdlViewer_Error_Report_must_be_loaded_prior_to_Rebuild_being_called", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsupported file extension for SaveAs.
        /// </summary>
        internal static string RdlViewer_Error_UnsupportedExtension {
            get {
                return ResourceManager.GetString("RdlViewer_Error_UnsupportedExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PDF files (*.pdf)|*.pdf|XML files (*.xml)|*.xml|HTML files (*.html)|*.html|CSV files (*.csv)|*.csv|RTF files (*.rtf)|*.rtf|TIF files (*.tif)|*.tif|Excel 2007 Table Only (*.xlsx)|*.xlsx|Excel 2007 (*.xlsx)|*.xlsx|MHT files (*.mht)|*.mht.
        /// </summary>
        internal static string RdlViewer_menuFileSaveAs_Click_FilesFilter {
            get {
                return ResourceManager.GetString("RdlViewer_menuFileSaveAs_Click_FilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid Report Parameter.
        /// </summary>
        internal static string RdlViewer_ParametersLeave_InvalidReportParameter {
            get {
                return ResourceManager.GetString("RdlViewer_ParametersLeave_InvalidReportParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report Parameter Missing.
        /// </summary>
        internal static string RdlViewer_ParametersViewClick_ReportParameterMissing {
            get {
                return ResourceManager.GetString("RdlViewer_ParametersViewClick_ReportParameterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter &apos;{0}&apos; is required but not provided..
        /// </summary>
        internal static string RdlViewer_ParametersViewClick_RequiredParameterNotProvided {
            get {
                return ResourceManager.GetString("RdlViewer_ParametersViewClick_RequiredParameterNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string RdlViewer_ShowD_Error {
            get {
                return ResourceManager.GetString("RdlViewer_ShowD_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Viewer property must be set prior to issuing FindNext..
        /// </summary>
        internal static string RdlViewerFind_ErrorA_PropertyMustSetPriorFindNext {
            get {
                return ResourceManager.GetString("RdlViewerFind_ErrorA_PropertyMustSetPriorFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Viewer property must be set prior to issuing FindPrevious..
        /// </summary>
        internal static string RdlViewerFind_ErrorA_PropertyMustSetPriorFindPrevious {
            get {
                return ResourceManager.GetString("RdlViewerFind_ErrorA_PropertyMustSetPriorFindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Phrase not found.
        /// </summary>
        internal static string RdlViewerFind_FindNext_Phrase_not_found {
            get {
                return ResourceManager.GetString("RdlViewerFind_FindNext_Phrase_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reached end of report, continued from top.
        /// </summary>
        internal static string RdlViewerFind_FindNext_Reached_end_of_report {
            get {
                return ResourceManager.GetString("RdlViewerFind_FindNext_Reached_end_of_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reached top of report, continued from end.
        /// </summary>
        internal static string RdlViewerFind_FindPrevious_Reached_top_of_report {
            get {
                return ResourceManager.GetString("RdlViewerFind_FindPrevious_Reached_top_of_report", resourceCulture);
            }
        }
    }
}
