//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Majorsilence.Reporting.RdlViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fyiReporting.RdlViewer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string DialogWait_Minutes {
            get {
                return ResourceManager.GetString("DialogWait_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string DialogWait_Seconds {
            get {
                return ResourceManager.GetString("DialogWait_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HyperLink Error.
        /// </summary>
        internal static string PageDrawing_OnMouseDown_HyperLinkError {
            get {
                return ResourceManager.GetString("PageDrawing_OnMouseDown_HyperLinkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to link to.
        /// </summary>
        internal static string PageDrawing_OnMouseDown_UnableLink {
            get {
                return ResourceManager.GetString("PageDrawing_OnMouseDown_UnableLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Pass key entered..
        /// </summary>
        internal static string RdlViewer_doPossibleDecryption_Incorrect_Pass_key_entered_ {
            get {
                return ResourceManager.GetString("RdlViewer_doPossibleDecryption_Incorrect_Pass_key_entered_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report must be loaded prior to Rebuild being called..
        /// </summary>
        internal static string RdlViewer_Error_Report_must_be_loaded_prior_to_Rebuild_being_called {
            get {
                return ResourceManager.GetString("RdlViewer_Error_Report_must_be_loaded_prior_to_Rebuild_being_called", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file extension for SaveAs.
        /// </summary>
        internal static string RdlViewer_Error_UnsupportedExtension {
            get {
                return ResourceManager.GetString("RdlViewer_Error_UnsupportedExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF files (*.pdf)|*.pdf|XML files (*.xml)|*.xml|HTML files (*.html)|*.html|CSV files (*.csv)|*.csv|RTF files (*.rtf)|*.rtf|TIF files (*.tif)|*.tif|Excel 2007 Table Only (*.xlsx)|*.xlsx|Excel 2007 (*.xlsx)|*.xlsx|MHT files (*.mht)|*.mht.
        /// </summary>
        internal static string RdlViewer_menuFileSaveAs_Click_FilesFilter {
            get {
                return ResourceManager.GetString("RdlViewer_menuFileSaveAs_Click_FilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Report Parameter.
        /// </summary>
        internal static string RdlViewer_ParametersLeave_InvalidReportParameter {
            get {
                return ResourceManager.GetString("RdlViewer_ParametersLeave_InvalidReportParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Parameter Missing.
        /// </summary>
        internal static string RdlViewer_ParametersViewClick_ReportParameterMissing {
            get {
                return ResourceManager.GetString("RdlViewer_ParametersViewClick_ReportParameterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is required but not provided..
        /// </summary>
        internal static string RdlViewer_ParametersViewClick_RequiredParameterNotProvided {
            get {
                return ResourceManager.GetString("RdlViewer_ParametersViewClick_RequiredParameterNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string RdlViewer_ShowD_Error {
            get {
                return ResourceManager.GetString("RdlViewer_ShowD_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer property must be set prior to issuing FindNext..
        /// </summary>
        internal static string RdlViewerFind_ErrorA_PropertyMustSetPriorFindNext {
            get {
                return ResourceManager.GetString("RdlViewerFind_ErrorA_PropertyMustSetPriorFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer property must be set prior to issuing FindPrevious..
        /// </summary>
        internal static string RdlViewerFind_ErrorA_PropertyMustSetPriorFindPrevious {
            get {
                return ResourceManager.GetString("RdlViewerFind_ErrorA_PropertyMustSetPriorFindPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase not found.
        /// </summary>
        internal static string RdlViewerFind_FindNext_Phrase_not_found {
            get {
                return ResourceManager.GetString("RdlViewerFind_FindNext_Phrase_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached end of report, continued from top.
        /// </summary>
        internal static string RdlViewerFind_FindNext_Reached_end_of_report {
            get {
                return ResourceManager.GetString("RdlViewerFind_FindNext_Reached_end_of_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached top of report, continued from end.
        /// </summary>
        internal static string RdlViewerFind_FindPrevious_Reached_top_of_report {
            get {
                return ResourceManager.GetString("RdlViewerFind_FindPrevious_Reached_top_of_report", resourceCulture);
            }
        }
    }
}
