name: windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build Release
        run: ./build-release.ps1
      - name: Test
        run: dotnet test -c Release MajorsilenceReporting.sln --verbosity normal --collect:"XPlat Code Coverage" --logger:"trx"
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure() # run this step even if previous step failed
        with:
          name: unit tests
          path: "**/TestResults/*.trx"
          reporter: dotnet-trx
      - name: SBOM
        uses: CycloneDX/gh-dotnet-generate-sbom@v1
        with:
          path: ./MajorsilenceReporting.sln
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            Release-Builds/build-output/*.zip
            Release-Builds/build-output/*.nupkg
            sbom.xml
          retention-days: 1
  mac-wine-package:
    runs-on: ubuntu-latest
    needs: windows-build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build-output
          path: /build-output/build.zip
      - name: Unzip build output
        run: unzip /build-output/build.zip -d /build-output
      - name: unzip rdl zip
        run: unzip /build-output/Release-Builds/build-output/*-majorsilence-reporting-designer-net8.0-windows-anycpu.zip.zip -d /build-output/Release-Builds/build-output
      - name: Create Package
        run: ./build-mac-wine-package.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-output
          path: |
            /build-output/macpackage-output/*.zip